name: Publish Swift Package

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-swift:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            repository: toeverything/Octobase
            ref: refs/heads/master
        - name: echo current directory
          run: |
            pwd
            echo "current directory structure"
            ls -R
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
              profile: minimal
              toolchain: stable
              override: true
        - name: Set up cargo cache
          uses: actions/cache@v3
          continue-on-error: false
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              ./vendor
              ./.cargo/config
              ./node_modules/.pnpm-store
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: ${{ runner.os }}-cargo-
        - name: build swift
          run: |
            cargo build -p jwst-swift-integrate --release
            ls -l apps/swift/OctoBaseSwift
        - uses: actions/upload-artifact@v3
          with:
            name: swift-build-output
            path: apps/swift/OctoBaseSwift
        - uses: actions/checkout@v3
          with:
            repository: toeverything/octobase-swift-binding
            ref: refs/heads/master
        - name: echo current directory
          run: |
            pwd
            echo "current directory structure"
            ls -R
        - run: mkdir "$(pwd)/temp"
        - uses: actions/download-artifact@v3
          with:
            name: swift-build-output
            path: ~/swift-build-output
        - run: |
            ls -R ~/swift-build-output
            git status
            git rm -rf RustXcframework.xcframework Sources
            git rm Package.swift
            git status
            cp -r ~/swift-build-output .
