name: test push

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: thorseraq/octobase-swift-binding
          ref: refs/heads/master
          token: ${{ secrets.octobase_swift_binding }}
      - name: Set up Git user
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
      - name: Make changes
        run: |
          touch demo.txt
      - name: Commit and push changes
        run: |
          ls -R
          git add .
          git commit -m "Update hello.txt"
          git remote -vv
          git push origin master